### ISSUE TITLE
Database (Epic)

### ISSUE THREAD

**Issue by bporter11** [Drabblesaur/CS178AProject#11]
**Description:**
- As a user I want to Store login information/Verification of users
- As a user I want to  have saved locations (favorite type of feature)
- As a user I want to Profile preferences (walking, biking, scooter, etc.)
- As a developer I want to store Metadata, frequented locations (expand on this)
- As a developer I want store Location keywords (shorthands, ex. ssc, wch, chung etc.)

**Exit Criteria:**
- [x] Research Databases and cloud hosting [Database Planning#10](https://github.com/Drabblesaur/CS178AProject/issues/10)
- [x] [Create mongoDB database (Story)#16](https://github.com/Drabblesaur/CS178AProject/issues/16)
- [ ] [Create Dummy Data when Accessing Login Page (Story)#15](https://github.com/Drabblesaur/CS178AProject/issues/15)

**Additional Information:**
