### ISSUE TITLE
App login page (Epic)

### ISSUE THREAD

**Issue by bporter11** [Drabblesaur/CS178AProject#6]
**Description:**
Design and implement a login page for users to enter their credentials and be forwarded to the main app page.

**Exit Criteria:**
- [ ] Username Box
- [ ] Password Box
- [ ] Reset password Button
- [ ] Find FOSS login authenticator
- [ ] Upon successful login -> foward to main app
- [ ] Failed login, try again feature
- [ ] [Login Developer Button (Story)#20](https://github.com/Drabblesaur/CS178AProject/issues/20)
- [ ] [Login verification (Story)#12](https://github.com/Drabblesaur/CS178AProject/issues/12)

**Additional Information:**
Dependent on x,y,z
Useful links
